export type {
  ContextBoardCustomKindCopy as WorkDesignBoardCustomKindCopy,
  ContextBoardDiagramLabelPreset as WorkDesignBoardDiagramLabelPreset,
  ContextBoardSelectionItem as WorkDesignBoardSelectionItem,
  ContextBoardStyleTarget as WorkDesignBoardStyleTarget,
  ContextBoardTemplateTray as WorkDesignBoardTemplateTray,
  ContextBoardTool as WorkDesignBoardTool,
  ContextBoardUmlRelationshipCopy as WorkDesignBoardUmlRelationshipCopy,
} from "../../../../product-apps/context-board/index.ts";

export {
  contextBoardBasicShapeKinds as workDesignBoardBasicShapeKinds,
  contextBoardC4PersonHeight as workDesignBoardC4PersonHeight,
  contextBoardConnectionTone as workDesignBoardConnectionTone,
  contextBoardConnectorGlowColor as workDesignBoardConnectorGlowColor,
  contextBoardConnectorLabelItem as workDesignBoardConnectorLabelItem,
  contextBoardConnectorMarkerId as workDesignBoardConnectorMarkerId,
  contextBoardConnectorMarkerStyle as workDesignBoardConnectorMarkerStyle,
  contextBoardConnectorPathStyle as workDesignBoardConnectorPathStyle,
  contextBoardCustomAutoHeight as workDesignBoardCustomAutoHeight,
  contextBoardCustomDetailRows as workDesignBoardCustomDetailRows,
  contextBoardCustomItemMinimumSize as workDesignBoardCustomItemMinimumSize,
  contextBoardCustomItemResolvedSize as workDesignBoardCustomItemResolvedSize,
  contextBoardCustomItemSize as workDesignBoardCustomItemSize,
  contextBoardCustomKindAutoSizesText as workDesignBoardCustomKindAutoSizesText,
  contextBoardCustomKindCopy as workDesignBoardCustomKindCopy,
  contextBoardCustomKindHasDetail as workDesignBoardCustomKindHasDetail,
  contextBoardCustomKindHasKicker as workDesignBoardCustomKindHasKicker,
  contextBoardCustomKindHasPorts as workDesignBoardCustomKindHasPorts,
  contextBoardCustomKindIsGeneral as workDesignBoardCustomKindIsGeneral,
  contextBoardCustomKindIsLabel as workDesignBoardCustomKindIsLabel,
  contextBoardCustomKindIsShape as workDesignBoardCustomKindIsShape,
  contextBoardCustomTextProfile as workDesignBoardCustomTextProfile,
  contextBoardDiagramArrangePosition as workDesignDiagramArrangePosition,
  contextBoardDiagramComponentKinds as workDesignDiagramComponentKinds,
  contextBoardDiagramCopy as workDesignDiagramCopy,
  contextBoardDiagramLabelPreset as workDesignBoardDiagramLabelPreset,
  contextBoardDiagramLabelPresets as workDesignBoardDiagramLabelPresets,
  contextBoardDiagramLabelSectionLabel as workDesignBoardDiagramLabelSectionLabel,
  contextBoardDiagramSharedToolKinds as workDesignBoardDiagramSharedToolKinds,
  contextBoardDiagramStarterItemSize as workDesignDiagramStarterItemSize,
  contextBoardDiagramStarterLabelItems as workDesignDiagramStarterLabelItems,
  contextBoardDiagramStarterTone as workDesignDiagramStarterTone,
  contextBoardDiagramStarterUsesIntrinsicCanvas as workDesignDiagramStarterUsesIntrinsicCanvas,
  contextBoardDiagramStarterViewportFocus as workDesignDiagramStarterViewportFocus,
  contextBoardDiagramToolLabel as workDesignDiagramToolLabel,
  contextBoardDiagramTypes as workDesignDiagramTypes,
  contextBoardDuplicatePosition as workDesignBoardDuplicatePosition,
  contextBoardEndpointFromPortElement as workDesignBoardEndpointFromPortElement,
  contextBoardEstimatedRows as workDesignBoardEstimatedRows,
  contextBoardGeneralComponentKinds as workDesignBoardGeneralComponentKinds,
  contextBoardGeneralItemKinds as workDesignBoardGeneralItemKinds,
  contextBoardItemsBounds as workDesignBoardItemsBounds,
  contextBoardItemsCenteredAt as workDesignBoardItemsCenteredAt,
  contextBoardKeyboardTargetIsEditable,
  contextBoardLabelKinds as workDesignBoardLabelKinds,
  contextBoardSketchPath as workDesignBoardSketchPath,
  contextBoardSketchToolCopy as workDesignBoardSketchToolCopy,
  contextBoardSnapshotToneColors as workDesignSnapshotToneColors,
  contextBoardStarterConnectionPoint as workDesignBoardStarterConnectionPoint,
  contextBoardStyleCopy as workDesignBoardStyleCopy,
  contextBoardStylePalettePosition as workDesignBoardStylePalettePosition,
  contextBoardStyleTargetSurface as workDesignBoardStyleTargetSurface,
  contextBoardTemplateTrayFromItems as workDesignTemplateTrayFromItems,
  contextBoardTemplateTrayMetrics as workDesignTemplateTrayMetrics,
  contextBoardUmlRelationshipCopy as workDesignBoardUmlRelationshipCopy,
  contextBoardUmlRelationships as workDesignBoardUmlRelationships,
} from "../../../../product-apps/context-board/index.ts";

export {
  workDesignC4StarterDetail,
  workDesignDependencyStarterDetail,
  workDesignDiagramStarterConnections,
  workDesignDiagramStarterItems,
  workDesignFlowchartStarterDetail,
  workDesignMindmapStarterDetail,
  workDesignSequenceStarterDetail,
  workDesignSwimlaneStarterDetail,
  workDesignUmlStarterDetail,
} from "./work-design-context-board-starters.ts";
